config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root to: "static_pages#index"

  resources :cohorts
  resources :courses
  resources :students
  resources :instructors

  post '/cohorts/:id/instructors/add' => 'cohorts#add_instructor'
  post '/cohorts/:id/instructors/delete' => 'cohorts#remove_instructor'
  post '/cohorts/:id/students/add' => 'cohorts#add_student'
  post '/cohorts/:id/students/delete' => 'cohorts#remove_student'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_and_belongs_to_many :students, -> { distinct }
  has_and_belongs_to_many :instructors, -> { distinct }
  belongs_to :course

end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_and_belongs_to_many :cohorts
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :cohorts
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  before_action :require_login

  def index
    @cohort = Cohort.new
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def create
    Cohort.create(cohort_params)
    redirect_to '/cohorts'
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end

  def update
    @cohort = Cohort.find(params[:id])
    @cohort.update(cohort_params)
    @cohort.save
    redirect_to '/cohorts'
  end

  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy
    redirect_to '/cohorts'
  end

  def add_instructor
    @cohort = Cohort.find(params[:id])
    @cohort.instructors << Instructor.find(params[:instructor_id])
    redirect_to @cohort
  end

  def remove_instructor
    @cohort = Cohort.find(params[:id])
    @cohort.instructors.delete Instructor.find(params[:instructor_id])
    redirect_to @cohort
  end

  def add_student
    @cohort = Cohort.find(params[:id])
    @cohort.students << Student.find(params[:student_id])
    redirect_to @cohort
  end

  def remove_student
    @cohort = Cohort.find(params[:id])
    @cohort.students.delete Student.find(params[:student_id])
    redirect_to @cohort
  end

  private
    def cohort_params
      params.require(:cohort).permit(:name, :start, :end, :course_id)
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :require_login


  def index
    @course = Course.new
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def create
    Course.create(course_params)
    redirect_to '/courses'
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    @course.update(course_params)
    @course.save
    redirect_to '/courses'
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to '/courses'
  end

  private
    def course_params
      params.require(:course).permit(:name, :hours, :description)
    end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  before_action :require_login


  def index
    @instructor = Instructor.new
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def create
    Instructor.create(instructor_params)
    redirect_to '/instructors'
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
    @instructor.update(instructor_params)
    @instructor.save
    redirect_to '/instructors'
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    redirect_to '/instructors'
  end

  private
    def instructor_params
      params.require(:instructor).permit(:name, :age, :salary, :education)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :require_login

  def index
    @student = Student.new
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def create
    Student.create(student_params)
    redirect_to '/students'
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    @student.save
    redirect_to '/students'
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to '/students'
  end

  private
    def student_params
      params.require(:student).permit(:name, :age, :education)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/cohorts/_form.html.erb
<%= form_for( @cohort ) do |f| %>
  <div class="flex">
    <div class="half">
      <%= label_tag 'name', "Name" %>
      <%= f.text_field(:name) %>
    </div>
    <div class="half">
      <%= label_tag 'course', "Course" %>
      <%= f.select :course_id, Course.all.collect { |c| [ c.name, c.id ] } %>
    </div>
  </div>
  <div class="flex">
    <div class="half">
      <%= label_tag 'start', "Start" %>
      <%= f.date_field(:start) %>
    </div>
    <div class="half">
      <%= label_tag 'end', "End" %>
      <%= f.date_field(:end) %>
    </div>
  </div>
  <div class="flex">
    <div class="off-half form-button  right-text">
      <button > Save </button>
    </div>
  </div>
<% end %>

app/views/cohorts/edit.html.erb
<h2>Edit Course </h2>
<%= render partial: '/cohorts/form', object: @cohort %>

app/views/cohorts/index.html.erb
<button id="show-form"> Create a Cohort</button>
<div id="form" class="hidden">
  <%= render partial: '/cohorts/form', object: @cohort %>
</div>
<h2>All Cohorts</h2>
<table class="primary">
  <thead>
    <tr>
      <th> ID </th>
      <th> Name </th>
      <th> Start </th>
      <th> End </th>
      <th> Course </th>
      <th> Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @cohorts.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= link_to  c.name, c, method: 'GET' %></td>
        <td><%= c.start %></td>
        <td><%= c.end %></td>
        <td><%= link_to  c.course.name, c.course, method: 'GET' %></td>
        <td class="right-text">
          <%= link_to  "Edit", edit_cohort_path(c), class: 'button warning', method: 'GET' %>
          <%= link_to  "Delete", c, class: 'button error', method: 'DELETE' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cohorts/show.html.erb
<article class="card">
  <header>
    <h3>#<%= @cohort.id %> - <%= @cohort.name %></h3>
  </header>
  <p><b>Course:</b> <%= @cohort.course.name %></p>
  <p><b>Description:</b> <%= @cohort.course.description %></p>
  <p><b><%= @cohort.start %> to <%= @cohort.end %></b></p>
  <footer>
    <%= link_to  "Edit", edit_cohort_path(@cohort), class: 'button warning' %>
    <%= link_to  "Delete", @cohort, class: 'button error', method: 'DELETE' %>
  </footer>
</article>

<h2>Instructors</h2>
<table class="primary">
  <thead>
    <tr>
      <th> ID </th>
      <th> Name </th>
      <th> Age </th>
      <th> Salary </th>
      <th> Education </th>
      <th> Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @cohort.instructors.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= link_to  c.name, c, method: 'GET' %></td>
        <td><%= c.age %></td>
        <td><%= c.salary %></td>
        <td><%= c.education %></td>
        <td class="right-text">
          <%= form_tag( "/cohorts/#{@cohort.id}/instructors/delete" , remote: false, method: 'POST') do |f| %>
            <%= hidden_field_tag :instructor_id, c.id %>
            <button class="error"> Remove from course </button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="flex">
  <div class="half off-half">
    <%= form_tag( "/cohorts/#{@cohort.id}/instructors/add" , remote: false, method: 'POST') do |f| %>
      <%= select_tag "instructor_id", options_from_collection_for_select(Instructor.all, "id", "name") %>
      <button class="success"> Add Instructor </button>
    <% end %>
  </div>
</div>
<br>
<h2>Students</h2>
<table class="primary">
  <thead>
    <tr>
      <th> ID </th>
      <th> Name </th>
      <th> Age </th>
      <th> Education </th>
      <th> Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @cohort.students.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= link_to  c.name, c, method: 'GET' %></td>
        <td><%= c.age %></td>
        <td><%= c.education %></td>
        <td class="right-text">
          <%= form_tag( "/cohorts/#{@cohort.id}/students/delete" , remote: false, method: 'POST') do |f| %>
            <%= hidden_field_tag :student_id, c.id %>
            <button class="error"> Remove from course </button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="flex">
  <div class="half off-half">
    <%= form_tag( "/cohorts/#{@cohort.id}/students/add" , remote: false, method: 'POST') do |f| %>
      <%= select_tag "student_id", options_from_collection_for_select(Student.all, "id", "name") %>
      <button class="success"> Add Student </button>
    <% end %>
  </div>
</div>

app/views/courses/_form.html.erb
<%= form_for( @course ) do |f| %>
  <div class="flex">
    <div class="half">
      <%= label_tag 'name', "Name" %>
      <%= f.text_field(:name) %>
    </div>
    <div class="half">
      <%= label_tag 'hours', "Hours" %>
      <%= f.number_field(:hours) %>
    </div>
  </div>
  <div>
    <%= label_tag 'description', "Description" %>
    <%= f.text_area :description  %>
  </div>
  <div class="flex">
    <div class="off-half form-button  right-text">
      <button > Save </button>
    </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h2>Edit Course </h2>
<%= render partial: '/courses/form', object: @course %>

app/views/courses/index.html.erb
<button id="show-form"> Create a Course</button>
<div id="form" class="hidden">
  <%= render partial: '/courses/form', object: @course %>
</div>
<h2>All Courses</h2>
<table class="primary">
  <thead>
    <tr>
      <th> ID </th>
      <th> Name </th>
      <th> Description </th>
      <th> Hours </th>
      <th> Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= link_to  c.name, c, method: 'GET' %></td>
        <td><%= c.description %></td>
        <td><%= c.hours %></td>
        <td class="right-text">
          <%= link_to  "Edit", edit_course_path(c), class: 'button warning', method: 'GET' %>
          <%= link_to  "Delete", c, class: 'button error', method: 'DELETE' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/show.html.erb
<article class="card">
  <header>
    <h3>#<%= @course.id %> - <%= @course.name %></h3>
  </header>
  <p><%= @course.description %></p>
  <p><b><%= @course.hours %> hrs</b></p>
  <footer>
    <%= link_to  "Edit", edit_course_path(@course), class: 'button warning' %>
    <%= link_to  "Delete", @course, class: 'button error', method: 'DELETE' %>
  </footer>
</article>

app/views/instructors/_form.html.erb
<%= form_for( @instructor ) do |f| %>
  <div class="flex">
    <div class="half">
      <%= label_tag 'name', "Name" %>
      <%= f.text_field(:name) %>
    </div>
    <div class="half">
      <%= label_tag 'age', "Age" %>
      <%= f.number_field(:age) %>
    </div>
  </div>
  <div class="flex">
   <div class="half">
      <%= label_tag 'salary', "Salary" %>
      <%= f.text_field(:salary) %>
    </div>
    <div class="half">
      <%= label_tag 'education', "Education" %>
      <%= f.select :education, ['High School', 'Bachelors', 'Masters', 'Phd', 'Self Taught'].collect { |c| [ c, c ] } %>
    </div>
  </div>
  <div class="flex">
    <div class="off-half form-button right-text">
      <button > Save </button>
    </div>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h2>Edit Instructor</h2>
<%= render partial: '/instructors/form', object: @instructor %>

app/views/instructors/index.html.erb
<button id="show-form"> Create an Instructor</button>
<div id="form" class="hidden">
  <%= render partial: '/instructors/form', object: @instructor %>
</div>
<h2>All Instructors</h2>
<table class="primary">
  <thead>
    <tr>
      <th> ID </th>
      <th> Name </th>
      <th> Age </th>
      <th> Salary </th>
      <th> Education </th>
      <th> Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @instructors.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= link_to  c.name, c, method: 'GET' %></td>
        <td><%= c.age %></td>
        <td><%= c.salary %></td>
        <td><%= c.education %></td>
        <td class="right-text">
          <%= link_to  "Edit", edit_instructor_path(c), class: 'button warning', method: 'GET' %>
          <%= link_to  "Delete", c, class: 'button error', method: 'DELETE' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/instructors/show.html.erb
<article class="card">
  <header>
    <h3>#<%= @instructor.id %> - <%= @instructor.name %></h3>
  </header>
  <p><b>Age: </b><%= @instructor.age %></p>
  <p><b>Salary: </b><%= @instructor.salary %></p>
  <p><b>Education: </b><%= @instructor.education %></p>
  <footer>
    <%= link_to  "Edit", edit_instructor_path(@instructor), class: 'button warning' %>
    <%= link_to  "Delete", @instructor, class: 'button error', method: 'DELETE'%>
  </footer>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School of Rock</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/picnic">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="flex center">
        <div class="left-header 600-half">
          <a href="/">
          <p class="title">School of Rock</p>
          </a>
        </div>
        <div class="600-half">
          <a href="/" class="button">Home</a>
          <a href="/cohorts" class="button">Cohorts</a>
          <a href="/courses" class="button">Courses</a>
          <a href="/instructors" class="button">Instructors</a>
          <a href="/students" class="button">Students</a>
        </div>
        <div class="right-header 600-one">
          <div class="flex center">
            <% if signed_in? %>
              <div>
                <p id="email">Signed in as: <%= current_user.email %></p>
              </div>
              <div>
                <%= button_to 'Sign out', sign_out_path, method: :delete %>
              </div>
            <% else %>
              <div>
                <%= link_to 'Sign in', sign_in_path, class: "button" %>
              </div>
            <% end %>
          </div>
        </div>

      </div>
    </nav>
    <center>
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
    </center>
    <div class="flex page-body">
      <div></div>
      <div>
        <%= yield %>
      </div>
      <div></div>
    </div>



  </body>
</html>

app/views/static_pages/index.html.erb
<center>
  <img src="https://media2.giphy.com/media/TZYw3OpCZAb2E/source.gif" alt="guitar"/>
</center>

app/views/students/_form.html.erb
<%= form_for( @student ) do |f| %>
  <div class="flex">
    <div class="half">
      <%= label_tag 'name', "Name" %>
      <%= f.text_field(:name) %>
    </div>
    <div class="half">
      <%= label_tag 'age', "Age" %>
      <%= f.number_field(:age) %>
    </div>
  </div>
  <div class="flex">
    <div class="half">
      <%= label_tag 'education', "Education" %>
      <%= f.select :education, ['High School', 'Bachelors', 'Masters', 'Phd', 'Self Taught'].collect { |c| [ c, c ] } %>
    </div>
  </div>
  <div class="flex">
    <div class="off-half form-button right-text">
      <button > Save </button>
    </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<h2>Edit Student</h2>
<%= render partial: '/students/form', object: @student %>

app/views/students/index.html.erb
<button id="show-form"> Create a Student</button>
<div id="form" class="hidden">
  <%= render partial: '/students/form', object: @student %>
</div>
<h2>All Students</h2>
<table class="primary">
  <thead>
    <tr>
      <th> ID </th>
      <th> Name </th>
      <th> Age </th>
      <th> Education </th>
      <th> Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= link_to  c.name, c, method: 'GET' %></td>
        <td><%= c.age %></td>
        <td><%= c.education %></td>
        <td class="right-text">
          <%= link_to  "Edit", edit_student_path(c), class: 'button warning', method: 'GET' %>
          <%= link_to  "Delete", c, class: 'button error', method: 'DELETE' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/show.html.erb
<article class="card">
  <header>
    <h3>#<%= @student.id %> - <%= @student.name %></h3>
  </header>
  <p><b>Age: </b><%= @student.age %></p>
  <p><b>Salary: </b><%= @student.salary %></p>
  <p><b>Education: </b><%= @student.education %></p>
  <footer>
    <%= link_to  "Edit", edit_student_path( @student), class: 'button warning' %>
    <%= link_to  "Delete", @student, class: 'button error', method: 'DELETE'%>
  </footer>
</article>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>